version: '3.8'
services:
  typing_speed_tester:
    container_name: typing_speed_tester
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"